/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/locations/{location_id}/intelligence': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get weather intelligence
     * @description Full deterministic weather intelligence — per-day risk, activity suitability, packing, and a trip summary — for a location and inclusive date range. `narrative` is always `null` here; narration is a separate call.
     */
    get: operations['get_intelligence_api_v1_locations__location_id__intelligence_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/locations/{location_id}/intelligence/best-days': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get best and worst days
     * @description Trip-level ranking view: the best and worst days to travel plus the overall risk level. A projection of the same computation as `/intelligence`.
     */
    get: operations['get_best_days_api_v1_locations__location_id__intelligence_best_days_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/locations/{location_id}/intelligence/packing': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get packing recommendations
     * @description Aggregated, deduplicated packing list for the whole trip, in a stable configured order. A projection of the same computation as `/intelligence`.
     */
    get: operations['get_packing_api_v1_locations__location_id__intelligence_packing_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/locations/{location_id}/weather/raw': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get raw normalized weather
     * @description Provider-normalized daily weather readings for a location and inclusive date range, without any intelligence processing. The response never identifies which upstream provider supplied the data.
     */
    get: operations['get_raw_weather_api_v1_locations__location_id__weather_raw_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/locations/{location_id}/intelligence/narrative': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Generate an AI narrative
     * @description Natural-language restatement of the deterministic intelligence for a location and date range. The AI only describes values that were already computed — it never creates or alters a risk level, score, ranking, or recommendation.
     */
    post: operations['generate_narrative_api_v1_locations__location_id__intelligence_narrative_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/providers/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get provider health
     * @description Operational availability of each upstream weather provider. Restricted to operator keys (`OPS_API_KEYS`). This is the only endpoint that names providers; weather data responses are always provider-agnostic.
     */
    get: operations['get_provider_health_api_v1_providers_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/conversations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List conversations
     * @description List all active conversations (for future multi-user support).
     */
    get: operations['list_conversations_api_v1_conversations_get']
    put?: never
    /**
     * Create a new conversation
     * @description Start a new conversation. Optionally include an initial message.
     */
    post: operations['create_conversation_api_v1_conversations_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/conversations/{conversation_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get conversation
     * @description Get a conversation with full message history.
     */
    get: operations['get_conversation_api_v1_conversations__conversation_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/conversations/chat': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Send a chat message
     * @description Send a message to the conversational travel assistant. If conversation_id is provided, continues that conversation. Otherwise starts a new one. Returns the assistant's response and updated trip context.
     */
    post: operations['chat_api_v1_conversations_chat_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Liveness probe
     * @description Unauthenticated liveness check. Does not verify downstream dependencies.
     */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * ActivitySuitabilitySchema
     * @description API Spec §9.4.4.
     */
    ActivitySuitabilitySchema: {
      /** Activity */
      activity: string
      /** Score */
      score: number
    }
    /**
     * BestDaysViewSchema
     * @description API Spec §9.7 — a projection of the same computation as §9.1.
     */
    BestDaysViewSchema: {
      location: components['schemas']['LocationSchema']
      period: components['schemas']['PeriodSchema']
      /** Bestdays */
      bestDays: string[]
      /** Worstdays */
      worstDays: string[]
      /** Overallrisklevel */
      overallRiskLevel: string
    }
    /**
     * ChatRequest
     * @description Chat message request.
     */
    ChatRequest: {
      /**
       * Message
       * @description User message
       */
      message: string
      /**
       * Conversationid
       * @description Existing conversation ID, or null to create new
       */
      conversationId?: string | null
    }
    /**
     * ChatResponse
     * @description Chat message response.
     */
    ChatResponse: {
      /**
       * Conversationid
       * Format: uuid
       */
      conversationId: string
      /** Response */
      response: string
      /** Contextcomplete */
      contextComplete: boolean
      /** Missingessentials */
      missingEssentials: string[]
      /** Tripcontext */
      tripContext: {
        [key: string]: unknown
      }
      /**
       * Intent
       * @description ChatIntent value classified for this turn.
       */
      intent: string
      /**
       * Llmgenerated
       * @description True when `response` came from Gemini; false for a deterministic template (clarification, date-range rejection, or an LLM-failure fallback).
       */
      llmGenerated: boolean
      /**
       * Places
       * @description Real places grounding this reply, from the backend Places provider. Empty when this turn fetched no attractions.
       */
      places?: components['schemas']['PlaceSchema'][]
      /**
       * Destinationcandidates
       * @description Populated only when `response` is a destination-disambiguation question; empty otherwise.
       */
      destinationCandidates?: components['schemas']['DestinationCandidateSchema'][]
    }
    /**
     * ConversationCreateRequest
     * @description Request to create a new conversation.
     */
    ConversationCreateRequest: {
      /**
       * Initialmessage
       * @description First user message
       */
      initialMessage?: string | null
    }
    /**
     * ConversationCreateResponse
     * @description Response after creating a conversation.
     */
    ConversationCreateResponse: {
      conversation: components['schemas']['ConversationSchema']
    }
    /**
     * ConversationListItem
     * @description Conversation summary for list views.
     */
    ConversationListItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Tripcontext */
      tripContext: {
        [key: string]: unknown
      }
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string
      /** Isactive */
      isActive: boolean
      /** Messagecount */
      messageCount: number
      /** Lastmessagepreview */
      lastMessagePreview?: string | null
    }
    /**
     * ConversationSchema
     * @description Conversation with full context and messages.
     */
    ConversationSchema: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Tripcontext */
      tripContext: {
        [key: string]: unknown
      }
      /** Messages */
      messages: components['schemas']['MessageSchema'][]
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string
      /** Isactive */
      isActive: boolean
    }
    /**
     * DailyIntelligenceSchema
     * @description API Spec §9.4.
     */
    DailyIntelligenceSchema: {
      /**
       * Date
       * Format: date
       */
      date: string
      summary: components['schemas']['DailySummarySchema']
      riskAssessment: components['schemas']['RiskAssessmentSchema']
      /** Activitysuitability */
      activitySuitability: components['schemas']['ActivitySuitabilitySchema'][]
      /** Packingrecommendations */
      packingRecommendations: string[]
      /** Traveladvisory */
      travelAdvisory: string
    }
    /**
     * DailySummarySchema
     * @description API Spec §9.4.1.
     */
    DailySummarySchema: {
      /** Tempminc */
      tempMinC: number
      /** Tempmaxc */
      tempMaxC: number
      /** Precipitationprobability */
      precipitationProbability: number
      /** Windspeedkph */
      windSpeedKph: number
      /** Condition */
      condition: string
    }
    /**
     * DestinationCandidateSchema
     * @description One candidate location for an ambiguous destination mention.
     *
     *     Structured form of the options listed in a clarification reply's
     *     `response` text — the frontend renders choices from this, never by
     *     parsing the message body.
     */
    DestinationCandidateSchema: {
      /** Name */
      name: string
      /** Displayname */
      displayName: string
      /** Latitude */
      latitude: number
      /** Longitude */
      longitude: number
      /** Country */
      country?: string | null
      /** Countrycode */
      countryCode?: string | null
      /** Admin1 */
      admin1?: string | null
    }
    /**
     * ErrorDetailSchema
     * @description API Spec §7.2 `ErrorDetail`.
     */
    ErrorDetailSchema: {
      /** Field */
      field: string
      /** Issue */
      issue: string
    }
    /**
     * ErrorSchema
     * @description API Spec §7.2. Never carries internal or provider detail.
     */
    ErrorSchema: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | 'VALIDATION_ERROR'
        | 'AUTHENTICATION_ERROR'
        | 'AUTHORIZATION_ERROR'
        | 'NOT_FOUND'
        | 'RATE_LIMITED'
        | 'PROVIDER_UNAVAILABLE'
        | 'UPSTREAM_TIMEOUT'
        | 'SERVICE_DEGRADED'
        | 'INTERNAL_ERROR'
      /** Message */
      message: string
      /** Details */
      details?: components['schemas']['ErrorDetailSchema'][] | null
    }
    /**
     * LocationSchema
     * @description API Spec §9.2.
     */
    LocationSchema: {
      /** Id */
      id: string
      /** Latitude */
      latitude: number
      /** Longitude */
      longitude: number
      /** Name */
      name?: string | null
    }
    /**
     * MessageSchema
     * @description Single message in a conversation.
     */
    MessageSchema: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Conversationid
       * Format: uuid
       */
      conversationId: string
      /** Role */
      role: string
      /** Content */
      content: string
      /** Metadata */
      metadata: {
        [key: string]: unknown
      }
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
    }
    /**
     * MetadataSchema
     * @description API Spec §9.12. Intentionally contains **no** provider identity.
     */
    MetadataSchema: {
      /**
       * Apiversion
       * @default 1.0
       */
      apiVersion: string
      /**
       * Generatedat
       * Format: date-time
       */
      generatedAt: string
      /** Requestid */
      requestId: string
      /** Cachestatus */
      cacheStatus?: ('hit' | 'miss' | 'stale') | null
      /** Ruleconfigversion */
      ruleConfigVersion?: string | null
      /** Degraded */
      degraded?: boolean | null
    }
    /**
     * NarrativeRequestSchema
     * @description API Spec §9.10 `NarrativeRequest`.
     */
    NarrativeRequestSchema: {
      /**
       * Startdate
       * Format: date
       * @description Inclusive range start (YYYY-MM-DD).
       */
      startDate: string
      /**
       * Enddate
       * Format: date
       * @description Inclusive range end (YYYY-MM-DD).
       */
      endDate: string
      /**
       * Language
       * @description Narration language; v1 supports 'en'.
       * @default en
       */
      language: string
    }
    /**
     * NarrativeSchema
     * @description API Spec §9.6.
     */
    NarrativeSchema: {
      /** Generatedbyllm */
      generatedByLlm: boolean
      /** Summarytext */
      summaryText: string
      /** Modelused */
      modelUsed?: string | null
      /** Fallbackused */
      fallbackUsed: boolean
    }
    /**
     * NarrativeViewSchema
     * @description Payload of `POST .../narrative` (API Spec §8.5).
     */
    NarrativeViewSchema: {
      location: components['schemas']['LocationSchema']
      period: components['schemas']['PeriodSchema']
      narrative: components['schemas']['NarrativeSchema']
    }
    /**
     * PackingViewSchema
     * @description API Spec §9.8 — a projection of the same computation as §9.1.
     */
    PackingViewSchema: {
      location: components['schemas']['LocationSchema']
      period: components['schemas']['PeriodSchema']
      /** Overallpackinglist */
      overallPackingList: string[]
    }
    /**
     * PeriodSchema
     * @description API Spec §9.3.
     */
    PeriodSchema: {
      /**
       * Startdate
       * Format: date
       */
      startDate: string
      /**
       * Enddate
       * Format: date
       */
      endDate: string
    }
    /**
     * PlaceSchema
     * @description A single real place backing a chat reply.
     *
     *     Always sourced from a `PlacesPort` call and the deterministic
     *     weather-aware ranking in `attraction_matching.py` — never from Gemini.
     *     Deliberately excludes the provider's internal id (an OSM node/way
     *     reference) and per-day grouping: this is a flat, frontend-independent
     *     reference list, not a projection of the provider's own record shape.
     */
    PlaceSchema: {
      /** Name */
      name: string
      /**
       * Type
       * @description AttractionType value, e.g. 'beach', 'museum'.
       */
      type: string
      /** Latitude */
      latitude?: number | null
      /** Longitude */
      longitude?: number | null
      /** Address */
      address?: string | null
      /**
       * Weathersuitability
       * @description WeatherSuitability value, e.g. 'ideal', 'poor'.
       */
      weatherSuitability: string
      /**
       * Reason
       * @description Deterministic, data-derived note on why this fits.
       */
      reason: string
    }
    /**
     * ProviderHealthSchema
     * @description API Spec §9.11.
     */
    ProviderHealthSchema: {
      /** Provider */
      provider: string
      /** Status */
      status: string
      /**
       * Lastcheckedat
       * Format: date-time
       */
      lastCheckedAt: string
    }
    /**
     * ProviderHealthViewSchema
     * @description Payload of `GET /providers/health` (API Spec §8.6).
     */
    ProviderHealthViewSchema: {
      /** Providers */
      providers: components['schemas']['ProviderHealthSchema'][]
    }
    /**
     * RawWeatherReadingSchema
     * @description API Spec §9.9.
     */
    RawWeatherReadingSchema: {
      /**
       * Date
       * Format: date
       */
      date: string
      /** Tempminc */
      tempMinC: number
      /** Tempmaxc */
      tempMaxC: number
      /** Precipitationprobability */
      precipitationProbability: number
      /** Precipitationmm */
      precipitationMm?: number | null
      /** Windspeedkph */
      windSpeedKph: number
      /** Humidity */
      humidity?: number | null
      /** Condition */
      condition: string
    }
    /**
     * RawWeatherViewSchema
     * @description Payload of `GET .../weather/raw` (API Spec §8.4).
     */
    RawWeatherViewSchema: {
      location: components['schemas']['LocationSchema']
      period: components['schemas']['PeriodSchema']
      /** Readings */
      readings: components['schemas']['RawWeatherReadingSchema'][]
    }
    /** ResponseEnvelope[BestDaysViewSchema] */
    ResponseEnvelope_BestDaysViewSchema_: {
      /** Success */
      success: boolean
      data: components['schemas']['BestDaysViewSchema'] | null
      metadata: components['schemas']['MetadataSchema']
      error?: components['schemas']['ErrorSchema'] | null
    }
    /** ResponseEnvelope[ChatResponse] */
    ResponseEnvelope_ChatResponse_: {
      /** Success */
      success: boolean
      data: components['schemas']['ChatResponse'] | null
      metadata: components['schemas']['MetadataSchema']
      error?: components['schemas']['ErrorSchema'] | null
    }
    /** ResponseEnvelope[ConversationCreateResponse] */
    ResponseEnvelope_ConversationCreateResponse_: {
      /** Success */
      success: boolean
      data: components['schemas']['ConversationCreateResponse'] | null
      metadata: components['schemas']['MetadataSchema']
      error?: components['schemas']['ErrorSchema'] | null
    }
    /** ResponseEnvelope[ConversationSchema] */
    ResponseEnvelope_ConversationSchema_: {
      /** Success */
      success: boolean
      data: components['schemas']['ConversationSchema'] | null
      metadata: components['schemas']['MetadataSchema']
      error?: components['schemas']['ErrorSchema'] | null
    }
    /** ResponseEnvelope[NarrativeViewSchema] */
    ResponseEnvelope_NarrativeViewSchema_: {
      /** Success */
      success: boolean
      data: components['schemas']['NarrativeViewSchema'] | null
      metadata: components['schemas']['MetadataSchema']
      error?: components['schemas']['ErrorSchema'] | null
    }
    /** ResponseEnvelope[PackingViewSchema] */
    ResponseEnvelope_PackingViewSchema_: {
      /** Success */
      success: boolean
      data: components['schemas']['PackingViewSchema'] | null
      metadata: components['schemas']['MetadataSchema']
      error?: components['schemas']['ErrorSchema'] | null
    }
    /** ResponseEnvelope[ProviderHealthViewSchema] */
    ResponseEnvelope_ProviderHealthViewSchema_: {
      /** Success */
      success: boolean
      data: components['schemas']['ProviderHealthViewSchema'] | null
      metadata: components['schemas']['MetadataSchema']
      error?: components['schemas']['ErrorSchema'] | null
    }
    /** ResponseEnvelope[RawWeatherViewSchema] */
    ResponseEnvelope_RawWeatherViewSchema_: {
      /** Success */
      success: boolean
      data: components['schemas']['RawWeatherViewSchema'] | null
      metadata: components['schemas']['MetadataSchema']
      error?: components['schemas']['ErrorSchema'] | null
    }
    /** ResponseEnvelope[WeatherIntelligenceSchema] */
    ResponseEnvelope_WeatherIntelligenceSchema_: {
      /** Success */
      success: boolean
      data: components['schemas']['WeatherIntelligenceSchema'] | null
      metadata: components['schemas']['MetadataSchema']
      error?: components['schemas']['ErrorSchema'] | null
    }
    /** ResponseEnvelope[list[ConversationListItem]] */
    ResponseEnvelope_list_ConversationListItem__: {
      /** Success */
      success: boolean
      /** Data */
      data: components['schemas']['ConversationListItem'][] | null
      metadata: components['schemas']['MetadataSchema']
      error?: components['schemas']['ErrorSchema'] | null
    }
    /**
     * RiskAssessmentSchema
     * @description API Spec §9.4.2.
     */
    RiskAssessmentSchema: {
      /** Overallrisklevel */
      overallRiskLevel: string
      /** Riskfactors */
      riskFactors: components['schemas']['RiskFactorSchema'][]
    }
    /**
     * RiskFactorSchema
     * @description API Spec §9.4.3. `rule` is the explainability anchor (NFR-1).
     */
    RiskFactorSchema: {
      /** Type */
      type: string
      /** Severity */
      severity: string
      /** Description */
      description: string
      /** Rule */
      rule: string
    }
    /**
     * TripSummarySchema
     * @description API Spec §9.5.
     */
    TripSummarySchema: {
      /** Bestdays */
      bestDays: string[]
      /** Worstdays */
      worstDays: string[]
      /** Overallpackinglist */
      overallPackingList: string[]
      /** Overallrisklevel */
      overallRiskLevel: string
      /** Tripsuitabilityscore */
      tripSuitabilityScore: number
      /** Travelconfidence */
      travelConfidence: number
    }
    /**
     * WeatherIntelligenceSchema
     * @description API Spec §9.1 — root payload of `GET .../intelligence`.
     *
     *     `narrative` is always `null` here; it is produced only by the separate
     *     `POST .../narrative` endpoint (API Spec §8.1 business rules).
     */
    WeatherIntelligenceSchema: {
      location: components['schemas']['LocationSchema']
      period: components['schemas']['PeriodSchema']
      /** Dailyintelligence */
      dailyIntelligence: components['schemas']['DailyIntelligenceSchema'][]
      tripSummary: components['schemas']['TripSummarySchema']
      narrative?: components['schemas']['NarrativeSchema'] | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_intelligence_api_v1_locations__location_id__intelligence_get: {
    parameters: {
      query: {
        /** @description Inclusive start. */
        startDate: string
        /** @description Inclusive end. */
        endDate: string
      }
      header?: never
      path: {
        /** @description Coordinate id, `"{lat},{lon}"` — e.g. `15.2993,74.1240`. */
        location_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseEnvelope_WeatherIntelligenceSchema_']
        }
      }
      /** @description Invalid coordinates or date range. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Missing or invalid API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description All weather providers unavailable and no stored data. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_best_days_api_v1_locations__location_id__intelligence_best_days_get: {
    parameters: {
      query: {
        /** @description Inclusive start. */
        startDate: string
        /** @description Inclusive end. */
        endDate: string
      }
      header?: never
      path: {
        /** @description Coordinate id, `"{lat},{lon}"` — e.g. `15.2993,74.1240`. */
        location_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseEnvelope_BestDaysViewSchema_']
        }
      }
      /** @description Invalid coordinates or date range. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Missing or invalid API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description All weather providers unavailable and no stored data. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_packing_api_v1_locations__location_id__intelligence_packing_get: {
    parameters: {
      query: {
        /** @description Inclusive start. */
        startDate: string
        /** @description Inclusive end. */
        endDate: string
      }
      header?: never
      path: {
        /** @description Coordinate id, `"{lat},{lon}"` — e.g. `15.2993,74.1240`. */
        location_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseEnvelope_PackingViewSchema_']
        }
      }
      /** @description Invalid coordinates or date range. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Missing or invalid API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description All weather providers unavailable and no stored data. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_raw_weather_api_v1_locations__location_id__weather_raw_get: {
    parameters: {
      query: {
        /** @description Inclusive start. */
        startDate: string
        /** @description Inclusive end. */
        endDate: string
      }
      header?: never
      path: {
        /** @description Coordinate id, `"{lat},{lon}"` — e.g. `15.2993,74.1240`. */
        location_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseEnvelope_RawWeatherViewSchema_']
        }
      }
      /** @description Invalid coordinates or date range. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Missing or invalid API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description All weather providers unavailable and no stored data. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  generate_narrative_api_v1_locations__location_id__intelligence_narrative_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Coordinate id, `"{lat},{lon}"` — e.g. `15.2993,74.1240`. */
        location_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NarrativeRequestSchema']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseEnvelope_NarrativeViewSchema_']
        }
      }
      /** @description Invalid body, coordinates, or language. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Missing or invalid API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Narration or weather data is temporarily unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_provider_health_api_v1_providers_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseEnvelope_ProviderHealthViewSchema_']
        }
      }
      /** @description Missing or invalid API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Key is not permitted for operator endpoints. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_conversations_api_v1_conversations_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseEnvelope_list_ConversationListItem__']
        }
      }
      /** @description Missing or invalid API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Service temporarily unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  create_conversation_api_v1_conversations_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ConversationCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseEnvelope_ConversationCreateResponse_']
        }
      }
      /** @description Missing or invalid API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Service temporarily unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_conversation_api_v1_conversations__conversation_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        conversation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseEnvelope_ConversationSchema_']
        }
      }
      /** @description Missing or invalid API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Conversation not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Service temporarily unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  chat_api_v1_conversations_chat_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseEnvelope_ChatResponse_']
        }
      }
      /** @description Missing or invalid API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Conversation not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Per-key rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Service temporarily unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
}
